use_frameworks!

platform :ios, '10.0'

target 'ZTQOIImage_Example' do
  pod 'ZTQOIImage', :path => '../'

  target 'ZTQOIImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
